import logging
import os

import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine

load_dotenv()

logger = logging.getLogger(__name__)

# Surrogate-key columns generated by PostgreSQL SERIAL — must not be sent
# from pandas or the INSERT will conflict with the sequence default.
_SK_COLS: dict[str, str] = {
    "dim_customer": "customer_key",
    "dim_product":  "product_key",
    "dim_seller":   "seller_key",
    "dim_location": "location_key",
    "fact_orders":  "order_key",
}

# Load order: dimensions before facts.
LOAD_ORDER = [
    "dim_date",
    "dim_customer",
    "dim_product",
    "dim_seller",
    "dim_location",
    "fact_orders",
]

# Truncate in reverse FK order so no constraint is violated.
_TRUNCATE_ORDER = [
    "fact_orders",
    "dim_date",
    "dim_customer",
    "dim_product",
    "dim_seller",
    "dim_location",
]


def _fix_extension_dtypes(df: pd.DataFrame) -> pd.DataFrame:
    """Convert pandas extension-array columns (Int8…Int64, boolean) to native
    Python object arrays so psycopg2 can adapt them.  pd.NA → None → NULL."""
    df = df.copy()
    for col in df.columns:
        if pd.api.types.is_extension_array_dtype(df[col].dtype):
            df[col] = df[col].where(df[col].notna(), other=None).astype(object)
    return df


def _build_engine() -> Engine:
    host     = os.getenv("DB_HOST",     "localhost")
    port     = os.getenv("DB_PORT",     "5432")
    dbname   = os.getenv("DB_NAME",     "olist_dwh")
    user     = os.getenv("DB_USER",     "postgres")
    password = os.getenv("DB_PASSWORD", "")
    url = f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{dbname}"
    return create_engine(url, future=True)


def _truncate_all(conn, schema: str) -> None:
    """Empty all tables in FK-safe order, resetting SERIAL sequences."""
    for table in _TRUNCATE_ORDER:
        conn.execute(text(f"TRUNCATE TABLE {schema}.{table} RESTART IDENTITY CASCADE"))
        logger.info("Truncated %s.%s", schema, table)
    conn.commit()


def load_to_db(
    transformed_data: dict[str, pd.DataFrame],
    schema: str = "olist_dw",
    chunksize: int = 5_000,
) -> None:
    """Truncate all DWH tables then append each transformed DataFrame."""
    engine = _build_engine()

    # --- Truncate phase: clears existing data without touching DDL/FKs ------
    logger.info("Truncating all tables before load …")
    with engine.connect() as conn:
        _truncate_all(conn, schema)

    # --- Load phase ----------------------------------------------------------
    for table_name in LOAD_ORDER:
        df = transformed_data.get(table_name)
        if df is None:
            logger.warning("Table %s not found in transformed data — skipping.", table_name)
            continue

        # Drop surrogate key column; PostgreSQL generates it via SERIAL.
        sk = _SK_COLS.get(table_name)
        if sk and sk in df.columns:
            df = df.drop(columns=[sk])

        df = _fix_extension_dtypes(df)

        rows = len(df)
        logger.info("Loading %-14s  rows=%d …", table_name, rows)

        df.to_sql(
            name=table_name,
            con=engine,
            schema=schema,
            if_exists="append",   # table structure and FKs are preserved
            index=False,
            chunksize=chunksize,
            method="multi",
        )

        logger.info("Loaded  %-14s  rows=%d  OK", table_name, rows)

    engine.dispose()
    logger.info("All tables loaded. Connection closed.")
